githubRepoOwner: carvierdotdev
githubRepoName: pymeforma-studio-increment
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: false
requireApproval: false
mergeMethod: merge
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
